### ISSUE TITLE
Set files should come from a common resource

### ISSUE THREAD

**Issue by terjekv** [EESSI/gentoo-overlay-old#37]
Right now we have multiple files for multiple architectures with very similar content: https://github.com/EESSI/gentoo-overlay/tree/master/etc/portage/sets 
This means that packages like rdma-core are listed in both of the files for linux, but not for macOS. Maintenance wise, this is not a good long-term solution. Having a single readable autorative source would be better. Maybe as YAML, with comments?

(And of course, a tool to generate the sets from the file is required.)

**Comment by bedroge** [comment]
Moved this to our new repo:
https://github.com/EESSI/gentoo-overlay/issues/4
