### ISSUE TITLE
collapse this forked repo into compatibility-layer repo

### ISSUE THREAD

**Issue by boegel** [EESSI/gentoo-overlay-old#40]
During the last EESSI meeting we briefly discussed that it doesn't make much sense anymore that we use a fork of the `ComputeCanada` repo.

Since this is effectively part of the compatibility layer, how about just moving the contents of this repo in there in a subdirectory?

**Comment by bedroge** [comment]
I don't think that will work, since the `eselect` tool (that we use to add the repo) expects that you give it a git repo:
https://wiki.gentoo.org/wiki/Eselect/Repository#Add_unregistered_repositories

**Comment by boegel** [comment]
Re-opening this, @bedroge is going to look into what needs to be changed to make this possible

**Comment by bedroge** [comment]
I just gave this a quick try.  The configuration file that you need for a repo should look like:

```
[eessi]
location = /tmp/gentoo/var/db/repos/eessi
sync-type = git
sync-uri = https://github.com/EESSI/compatibility-layer.git
```

I had something in mind where we could maybe change the `location` and include the subdir for our overlay there, but that obviously doesn't work, as this is the location where the `git clone` is being run, e.g.:
```
$ emerge --sync eessi
>>> Syncing repository 'eessi' into '/tmp/gentoo/var/db/repos/eessi'...
/tmp/gentoo/usr/bin/git clone --depth 1 "https://github.com/EESSI/compatibility-layer.git" .
Cloning into '.'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 40 (delta 4), reused 17 (delta 1), pack-reused 0
Receiving objects: 100% (40/40), 52.59 KiB | 656.00 KiB/s, done.
Resolving deltas: 100% (4/4), done.
=== Sync completed for eessi
!!! Repository 'eessi' is missing masters attribute in '/tmp/gentoo/var/db/repos/eessi/metadata/layout.conf'
!!! Set 'masters = gentoo' in this file for future compatibility
```

So it also expects the metadata folder in the root. Now we can do very ugly hacks like doing the clone ourselves in some other location and making a symlink to the overlay folder in `var/db/repos`, but I don't think we should go down that road...

**Comment by bedroge** [comment]
Shall I, for now, just create a new repo (maybe `eessi-overlay` or `eessi-gentoo-overlay` instead of `gentoo-overlay`?) and only add the things that we really need?

**Comment by bedroge** [comment]
Done! (gentoo-overlay)
